### ISSUE TITLE
Figure out where to start

### ISSUE THREAD

**Issue by ajtran303** [the-turing-index/api#1]
For the first phase of our MVP,

- [x] Pick a Python web framework - Django or Flask?
- [x] Pick a testing framework - Keep above 25%
- [x] Learn how to write API Specs for Python APIs
- [x] Learn how to consume the Google Calendar API
- [x] Read the Google Calendar Documentation
- [x] Figure out how to SEND JSON with our framework

**Comment by ajtran303** [comment]
When we pick a framework, we should figure out how to do a "Hello World" and maybe test it too.

**Comment by ajtran303** [comment]
We have been formulating a plan about mid-level design for the Phase 1 MVP

We will create a Google Account for an "Indexer" user who will subscribe to all the Turing Calendars (8).
That way, we will have access to this neat Google Calendar Endpoint called `CalendarList`
We will probable have to consume the `CalendarList`, `Calendars`, and `Events` endpoints

Flask is a good out-of-the-box framework for making a JSON API. 
It even comes with documentation on how to write API tests.

**Comment by michaeljevans** [comment]
We're looking at using [pry.py](https://github.com/Mic92/pry.py) for debugging purposes.

**Comment by ajtran303** [comment]
We will use Python Version 3.8.6 and Flask version 1.1.2

**Comment by ajtran303** [comment]
Regarding testing: 

[this tutorial](https://flask.palletsprojects.com/en/1.1.x/testing/) is pretty comprehensive and gives an example of how to test a Flask JSON API

**Comment by michaeljevans** [comment]
This [tutorial](https://flask.palletsprojects.com/en/1.1.x/tutorial/) may be a useful resource for familiarizing ourselves with the Flask framework. It walks through the process of setting up a basic blog application.

**Comment by ajtran303** [comment]
To see what testing looks like, follow this [tutorial README](https://github.com/pallets/flask/tree/1.1.2/examples/tutorial)

I have summarized the steps below:

```
git clone https://github.com/pallets/flask
cd flask
git checkout 1.1.2 && git switch -c 1.1.2
cd examples/tutorial

python3 -m venv venv
. venv/bin/activate

pip install -e .

pip install '.[test]'
pytest
```

To generate coverage:

```
coverage run -m pytest
coverage report
open htmlcov/index.html
```
