### ISSUE TITLE
Consume the Google Calendar API

### ISSUE THREAD

**Issue by ajtran303** [the-turing-index/api#8]
This can be broken down into several steps
- [x] Find the package for making HTTP requests
- [x] Find one calendar from Turing and look for an `event` resource
- [x] navigate the data structure to find what we need
- [ ] figure out what to do with that data (store it in a database or no?)

**Comment by ajtran303** [comment]
There's is a package called `requests` that I have been spiking on in interactive mode: https://requests.readthedocs.io/en/latest/user/quickstart/

**Comment by michaeljevans** [comment]
Config/Environment info here: https://flask.palletsprojects.com/en/1.1.x/api/#flask.Config
It looks like there are several different ways to add environment variables

**Comment by michaeljevans** [comment]
This may be a helpful package for serialization: https://pypi.org/project/flask-serialize/
The examples only show database models being serialized, but I am willing to bet we can use it for POPOs too

**Comment by ajtran303** [comment]
cURL request that worked

```
curl \
  'https://www.googleapis.com/calendar/v3/calendars/casimircreative.com_59k8msrrc2ddhcv787vubvp0s4%40group.calendar.google.com/events?orderBy=startTime&singleEvents=true&timeMax=2020-10-27T22%3A01%3A46%2B00%3A00&timeMin=2020-10-05T03%3A00%3A00%2B00%3A00&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```

HTTP request
```
GET https://www.googleapis.com/calendar/v3/calendars/casimircreative.com_59k8msrrc2ddhcv787vubvp0s4%40group.calendar.google.com/events?orderBy=startTime&singleEvents=true&timeMax=2020-10-27T22%3A01%3A46%2B00%3A00&timeMin=2020-10-05T03%3A00%3A00%2B00%3A00&key=[YOUR_API_KEY] HTTP/1.1

Authorization: Bearer [YOUR_ACCESS_TOKEN]
Accept: application/json
```

[Here is the response](https://github.com/the-turing-index/api/files/5448382/response.txt)

**Comment by michaeljevans** [comment]
[Here's a gist](https://gist.github.com/michaeljevans/6c023086eef9cdacd38a39b5a48b53aa) on how we might approach consuming Google Calendar data and repackaging it into an appropriate response for the front end.

**Comment by ajtran303** [comment]
Should we throw any of this data into a database?
